language: node_js
node_js:
- '0.10'
env:
  global:
  - GH_REF: github.com/chad-autry/client-auth-jwt
deploy:
   provider: npm
   email: "chad.autry@gmail.com"
   api_key: "$NPM_TOKEN"
   on:
     tags: true
